github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
tasks:
  - before: git config --global user.email $GIT_COMMITTER_EMAIL
