apiVersion: v2
name: minecraft-server
version: 0.1.1000
appVersion: v0.1.10
description: Docker Minecraft Server image with support for Plugins etc.
home: https://github.com/qumine/minecraft-server
keywords:
- games
- game-server
- minecraft
- qumine
sources:
- https://github.com/qumine/minecraft-server
maintainers:
- name: QuHive
  email: dev@quhive.dev
icon: https://avatars.githubusercontent.com/u/73256940?s=200&v=4
engine: gotpl
annotations:
  catalog.cattle.io/display-name: "Minecraft Server"
