apiVersion: v1
kind: Service
metadata:
  name: {{ template "qumine.fullname" . }}
  labels: {{ include "qumine.labels" . | nindent 4 }}
  {{- if .Values.qumine.deployment.service.labels -}}
  {{ toYaml .Values.qumine.deployment.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.qumine.deployment.service.annotations }}
  annotations: {{ toYaml .Values.qumine.deployment.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.qumine.deployment.service.clusterIP }}
  clusterIP: {{ .Values.qumine.deployment.service.clusterIP }}
  {{- end }}
  {{- if .Values.qumine.deployment.service.externalIPs }}
  externalIPs: {{ toYaml .Values.qumine.deployment.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.qumine.deployment.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.qumine.deployment.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.qumine.deployment.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.qumine.deployment.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.qumine.deployment.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.qumine.deployment.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
  - name: ingress
    port: {{ .Values.qumine.deployment.service.port }}
    protocol: TCP
    targetPort: ingress
    {{- if and (eq .Values.qumine.deployment.service.type "NodePort") (not (empty .Values.qumine.deployment.service.nodePort)) }}
    nodePort: {{ .Values.qumine.deployment.service.nodePort  }}
    {{- end }}
  selector: {{ include "qumine.matchLabels" . | nindent 4 }}
  type: {{ .Values.qumine.deployment.service.type }}
