{{- if (eq .Values.persistence.type "StorageClass") -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ template "qumine.fullname" . }}-metrics"
  labels: {{ include "qumine.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- if .Values.persistence.retainPersistentVolumeClaim }}
    helm.sh/resource-policy: "keep"
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
