{{- if .Values.qumine.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "minecraft.fullname" . }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
        app: {{ template "minecraft.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end -}}